name = "POMDPs"
uuid = "a93abf59-7444-517b-a68a-c42f96afdd7d"
repo = "https://github.com/JuliaPOMDP/POMDPs.jl.git"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
